# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 675, 675))
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setRowCount(9)
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(75)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew_Game = QtWidgets.QMenu(self.menuFile)
        self.menuNew_Game.setObjectName("menuNew_Game")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSolve = QtWidgets.QAction(MainWindow)
        self.actionSolve.setObjectName("actionSolve")
        self.actionEasy = QtWidgets.QAction(MainWindow)
        self.actionEasy.setObjectName("actionEasy")
        self.actionMedium = QtWidgets.QAction(MainWindow)
        self.actionMedium.setObjectName("actionMedium")
        self.actionHard = QtWidgets.QAction(MainWindow)
        self.actionHard.setObjectName("actionHard")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionHint = QtWidgets.QAction(MainWindow)
        self.actionHint.setObjectName("actionHint")
        self.actionShow_Candidates = QtWidgets.QAction(MainWindow)
        self.actionShow_Candidates.setObjectName("actionShow_Candidates")
        self.menuNew_Game.addAction(self.actionEasy)
        self.menuNew_Game.addAction(self.actionMedium)
        self.menuNew_Game.addAction(self.actionHard)
        self.menuFile.addAction(self.menuNew_Game.menuAction())
        self.menuFile.addAction(self.actionSolve)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionHint)
        self.menuEdit.addAction(self.actionShow_Candidates)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuNew_Game.setTitle(_translate("MainWindow", "New Game"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSolve.setText(_translate("MainWindow", "Solve"))
        self.actionEasy.setText(_translate("MainWindow", "Easy"))
        self.actionMedium.setText(_translate("MainWindow", "Medium"))
        self.actionHard.setText(_translate("MainWindow", "Hard"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionHint.setText(_translate("MainWindow", "Hint"))
        self.actionShow_Candidates.setText(_translate("MainWindow", "Show Candidates"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
